# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFrbgcjZJ09zStTwNhZsw-42JT4hGCb7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import gradio as gr

df = pd.read_csv("diabetic_data.csv")
df["readmitted"] = df["readmitted"].apply(lambda x: 1 if x == "<30" else 0)

def get_overview():
    total_patients = len(df)
    readmitted = int(df["readmitted"].sum())
    not_readmitted = int(total_patients - readmitted)

    return f"""
Total Patients: {total_patients}
Readmitted (<30 days): {readmitted}
Not Readmitted: {not_readmitted}
"""

def readmission_plot():
    fig, ax = plt.subplots(figsize=(6, 4))
    df["readmitted"].value_counts().sort_index().plot(kind="bar", ax=ax)
    ax.set_title("Readmission Distribution")
    ax.set_xlabel("Readmitted")
    ax.set_ylabel("Count")
    plt.tight_layout()
    return fig

def hospital_stay_plot():
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.hist(df["time_in_hospital"].dropna(), bins=20)
    ax.set_title("Time in Hospital Distribution")
    ax.set_xlabel("Days")
    ax.set_ylabel("Frequency")
    plt.tight_layout()
    return fig

def medication_plot():
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.hist(df["num_medications"].dropna(), bins=20)
    ax.set_title("Number of Medications Distribution")
    ax.set_xlabel("Medications")
    ax.set_ylabel("Frequency")
    plt.tight_layout()
    return fig

def heatmap_plot():
    cols = [
        "readmitted",
        "time_in_hospital",
        "num_lab_procedures",
        "num_medications",
        "number_outpatient",
        "number_emergency",
        "number_inpatient",
        "number_diagnoses"
    ]
    available_cols = [c for c in cols if c in df.columns]
    corr = df[available_cols].corr()

    fig, ax = plt.subplots(figsize=(8, 6))
    cax = ax.matshow(corr, aspect="auto")
    fig.colorbar(cax)
    ax.set_xticks(range(len(available_cols)))
    ax.set_yticks(range(len(available_cols)))
    ax.set_xticklabels(available_cols, rotation=45, ha="left")
    ax.set_yticklabels(available_cols)
    ax.set_title("Correlation Heatmap", pad=20)
    plt.tight_layout()
    return fig

def model_results():
    return pd.DataFrame({
        "Model": ["Logistic Regression", "Random Forest", "XGBoost", "Naive Bayes"],
        "AUC Score": [0.60, 0.59, 0.62, 0.58]
    })

def predict_risk(
    time_in_hospital,
    num_medications,
    number_inpatient,
    number_emergency,
    number_diagnoses
):
    score = (
        0.1 * time_in_hospital
        + 0.1 * num_medications
        + 0.3 * number_inpatient
        + 0.2 * number_emergency
        + 0.1 * number_diagnoses
    )
    prob = 1 / (1 + np.exp(-score / 10))
    risk = "High Risk of Readmission" if prob > 0.5 else "Low Risk"

    return {
        "Risk Probability": round(float(prob), 3),
        "Prediction": risk
    }

with gr.Blocks() as demo:
    gr.Markdown("# Hospital Readmission Prediction Dashboard")

    with gr.Tab("Overview"):
        gr.Textbox(value=get_overview(), label="Dataset Summary", lines=5)
        gr.Plot(value=readmission_plot)

    with gr.Tab("EDA"):
        gr.Plot(value=hospital_stay_plot)
        gr.Plot(value=medication_plot)
        gr.Plot(value=heatmap_plot)
        gr.Dataframe(value=model_results(), label="Model Comparison")

    with gr.Tab("Prediction Tool"):
        time_in_hospital = gr.Slider(1, 14, value=5, step=1, label="Time in Hospital")
        num_medications = gr.Slider(1, 50, value=10, step=1, label="Number of Medications")
        number_inpatient = gr.Slider(0, 10, value=0, step=1, label="Previous Inpatient Visits")
        number_emergency = gr.Slider(0, 10, value=0, step=1, label="Emergency Visits")
        number_diagnoses = gr.Slider(1, 16, value=5, step=1, label="Number of Diagnoses")

        predict_button = gr.Button("Predict Readmission Risk")
        output = gr.JSON(label="Prediction Output")

        predict_button.click(
            fn=predict_risk,
            inputs=[
                time_in_hospital,
                num_medications,
                number_inpatient,
                number_emergency,
                number_diagnoses
            ],
            outputs=output
        )

demo.launch()